// <auto-generated />
using System;
using ConsoleApp1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(DaiHocDBContext))]
    [Migration("20240418011852_initdb")]
    partial class initdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp1.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("ConsoleApp1.Models.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KhoaMaKhoa")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nganh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("KhoaMaKhoa");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("ConsoleApp1.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSinhVien"));

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LopMaLop")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaLop")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("LopMaLop");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("ConsoleApp1.Models.Lop", b =>
                {
                    b.HasOne("ConsoleApp1.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("KhoaMaKhoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("ConsoleApp1.Models.SinhVien", b =>
                {
                    b.HasOne("ConsoleApp1.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("LopMaLop");

                    b.Navigation("Lop");
                });
#pragma warning restore 612, 618
        }
    }
}
